name: CyFeng16 GitHub Readme Stats
'on':
  schedule:
    - cron: 0 0 * * *
jobs:
  update-gist:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependency
        run: '-| npm install'
      - name: Update readme
        run: |-
          ./node_modules/ts-node/dist/bin.js src/index.ts
          cat README.md
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'
          TIMEZONE: Asia/Shanghai
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "cy.z.feng@gmail.com"
          git config --global user.name "CyFeng16"
          git pull
          git add -A
          git commit -m "Updated content" || exit 0
          git push
